- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 #This is number
    COURSE: "DevSecOps with AWS" #string
    IS_LIVE: true #boolean
    TOOLS: #list referred as []
    - Linux
    - Shell
    - Ansible 
    CONCEPTS: #map or dictionary or object. referred like {}
      CI: Jenkins
      SCRIPTING: "Shell,Ansible,Terraform,Python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is: {{ DURATION }}, is live {{ IS_LIVE }}, tools are: {{ TOOLS }}, Concepts are: {{ CONCEPTS }}"

  
