- name: Conditions demo
  hosts: local
  connection: local
  vars:
    NUMBER: 78
  tasks:
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than or equal to 100"
    when: NUMBER < 100

  - name: print if the number is greater than r equal to 100
    ansible.builtin.debug:
      msg: "Given number is {{ NUMBER }} is greater than or equal to 100"
    when: NUMBER > 100

    