- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, Suresh, Raheem, Joseph"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into lists
    vars:
      course:
        name: ansible
        duration: 10HR
        tariner: sivakumar 
    ansible.builtin.debug:
      msg: "course info {{ course | dict2items}}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'tariner', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info {{ course | items2dict }}"